In [1]:
import torch
import torch.nn as nn

In [2]:
prediction = torch.randn(4, 5)

In [3]:
label = torch.randn(4, 5)

In [4]:
mse = nn.MSELoss(reduction = 'mean')

In [5]:
loss = mse(prediction, label)

In [6]:
loss

tensor(1.6878)

In [7]:
((prediction-label)**2).mean()

tensor(1.6878)

In [8]:
prediction

tensor([[ 0.7432, -0.3453, -0.4920, -0.6573,  0.9105],
        [ 1.0449,  0.9761,  1.4478, -0.0908,  0.6256],
        [ 0.3394,  2.4997,  0.2582,  1.0676, -0.1858],
        [-0.8424,  0.2435,  0.7354, -0.5448,  0.9920]])

In [9]:
label = torch.zeros(4, 5).random_(0,2)

In [10]:
label

tensor([[1., 0., 1., 0., 0.],
        [1., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [1., 0., 0., 1., 0.]])

In [11]:
sigmoid = nn.Sigmoid()

In [12]:
bce = nn.BCELoss(reduction = 'mean')

In [13]:
bce(sigmoid(prediction), label)

tensor(0.9628)

In [14]:
bces = nn.BCEWithLogitsLoss(reduction = 'mean')

In [15]:
bces(prediction, label)

tensor(0.9628)

In [16]:
import numpy as np

In [17]:
x = prediction.numpy()

In [18]:
y = label.numpy()

In [21]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [23]:
x

array([[ 0.7432184 , -0.34534374, -0.49197358, -0.65725815,  0.9105229 ],
       [ 1.0449255 ,  0.9761345 ,  1.4477737 , -0.0907654 ,  0.62562156],
       [ 0.3394345 ,  2.4997199 ,  0.25816426,  1.0676193 , -0.18584526],
       [-0.84244233,  0.24349982,  0.73541737, -0.54482067,  0.99195796]],
      dtype=float32)

In [25]:
x = sigmoid(x)

In [26]:
loss_values = []

In [27]:
for i in range(len(y)):
    batch_loss = []
    for j in range(len(y[0])):
        batch_loss.append(-np.log(x[i][j]) if y[i][j] == 1 else -np.log(1-x[i][j]))
    loss_values.append(batch_loss)
print(np.mean(loss_values))

0.9628049
