In [1]:
import torch
import torch.nn as nn

In [3]:
layer = nn.Linear(5, 5)

In [4]:
layer.weight

Parameter containing:
tensor([[-0.1954,  0.2297, -0.1800,  0.2334, -0.1417],
        [-0.1007,  0.1924, -0.3179,  0.1775,  0.0513],
        [ 0.0725,  0.1330, -0.4271, -0.3325,  0.0179],
        [ 0.2060,  0.0503, -0.0085, -0.2287,  0.2228],
        [ 0.0598, -0.3834, -0.3930,  0.1329, -0.4111]], requires_grad=True)

In [5]:
layer.weight.data

tensor([[-0.1954,  0.2297, -0.1800,  0.2334, -0.1417],
        [-0.1007,  0.1924, -0.3179,  0.1775,  0.0513],
        [ 0.0725,  0.1330, -0.4271, -0.3325,  0.0179],
        [ 0.2060,  0.0503, -0.0085, -0.2287,  0.2228],
        [ 0.0598, -0.3834, -0.3930,  0.1329, -0.4111]])

In [7]:
nn.init.uniform_(layer.weight.data, a=0.0, b=3)

tensor([[1.9780e+00, 1.2720e+00, 1.0162e+00, 1.0510e+00, 1.6901e+00],
        [2.6599e+00, 1.6096e+00, 2.6000e-01, 2.0379e+00, 2.1774e+00],
        [3.1829e-05, 1.3184e+00, 1.9003e+00, 2.1069e+00, 1.8923e-01],
        [1.0218e-02, 1.6366e+00, 2.7292e+00, 6.1437e-01, 1.9593e+00],
        [2.6036e+00, 3.0797e-01, 4.6939e-01, 3.2350e-01, 1.7985e-01]])

In [8]:
nn.init.normal_(layer.weight, mean = 0.0, std = 1.0)

Parameter containing:
tensor([[-1.5851,  0.7835, -1.9894,  1.5863,  0.6232],
        [ 1.1750, -0.1563, -1.3838,  0.2784, -0.4620],
        [-1.6764, -0.8696,  0.3631, -0.6469,  0.7046],
        [ 1.1078,  0.7414,  0.0562, -0.0087,  0.8731],
        [-0.3435, -0.7580, -0.4176,  0.4362, -1.9865]], requires_grad=True)

In [9]:
nn.init.normal_(layer.weight, mean = 0.0, std = 0.2)

Parameter containing:
tensor([[-0.3406,  0.0132,  0.0832,  0.0689,  0.0905],
        [-0.0740,  0.0010,  0.1659, -0.2066,  0.4885],
        [-0.1071,  0.1355,  0.0358, -0.1133, -0.1079],
        [ 0.4756,  0.2571,  0.2053,  0.1717, -0.0415],
        [-0.1579,  0.4278, -0.1446, -0.2771,  0.4243]], requires_grad=True)

In [10]:
nn.init.constant_(layer.weight, 8)

Parameter containing:
tensor([[8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.]], requires_grad=True)

In [11]:
nn.init.zeros_(layer.bias)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [12]:
layer.bias

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [13]:
layer.weight

Parameter containing:
tensor([[8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.]], requires_grad=True)

In [14]:
nn.init.xavier_uniform_(layer.weight, gain = 1.0)

Parameter containing:
tensor([[ 0.7384,  0.3204,  0.2034,  0.0207, -0.0144],
        [-0.5729,  0.1227, -0.3260,  0.1301, -0.1572],
        [ 0.3872, -0.6613,  0.0191, -0.5542,  0.3982],
        [ 0.4367,  0.6022, -0.1434, -0.2487,  0.1292],
        [-0.3093, -0.4203,  0.4205, -0.1372, -0.7634]], requires_grad=True)

In [15]:
nn.init.xavier_normal_(layer.weight, gain = 1.0)

Parameter containing:
tensor([[-0.7105,  0.1331,  0.7041, -0.5193,  0.0953],
        [-0.6904,  0.0398, -0.2588, -0.1978, -0.0096],
        [ 0.0745,  0.2349,  0.4172,  0.9199, -0.0855],
        [-0.8838,  0.4733, -0.3921, -0.2067, -0.0564],
        [-0.4322,  0.2472,  0.4912, -0.4718,  0.3943]], requires_grad=True)